### ISSUE TITLE
Feature Request: Add arm64 builds

### ISSUE THREAD

**Issue by cablespaghetti** [mopidy/apt#1]
Hi,

I've just installed the arm64 version of Ubuntu 20.04 on my Raspberry Pi 4. It would be great if this repository also provided arm64 builds. I'm happy to use my Raspberry Pi as a build server if it would help.

Thanks
Sam

**Comment by kingosticks** [comment]
FYI there are no libspotify arm64 builds available.

**Comment by jodal** [comment]
There are no `libspotify` builds for arm64, and there probably never will be as libspotify has been deprecated for years. Thus, the `python-spotify` package (aka `pyspotify`) cannot be built on arm64, and following from that, the `mopidy-spotify` package doesn't make sense to ship on arm64.

For all the other packages though, there is now an arm64 architecture on apt.mopidy.com.

Please give it a spin and report back if it works as expected!

**Comment by cablespaghetti** [comment]
Thanks for the speedy response both! I need Spotify support unfortunately, but it turns out you can run 32 bit ARM Docker images on an arm64 host. This might the workaround I need...

**Comment by MichaIng** [comment]
@jodal 
Many thanks from my side as well! If it can be achieved without much extra work, would you mind to make arm64 builds available on the Stretch suite, too?
