### ISSUE TITLE
Backport packages for Bullseye 

### ISSUE THREAD

**Issue by peter-vanpoucke** [mopidy/apt#10]
This question is related with issue #5. Since the plan is that the packages will be part of Debian Bullseye. At the moment the packages have a newer version for buster, then the release for bullseye. Are there any plans to add a backports distribution for Bullseye?

A few other questions that pop up: Is it safe to keep on using the buster packages for bullseye for the time being? Is it possible to maintain the nonfree packages for Debian Bullseye here?

**Comment by kingosticks** [comment]
Maybe I misunderstand what you are asking here but to clarify. All our free packages are included in all Debian releases, the version included is whatever was latest at the time of Debian's package freeze. That includes Debian Bullseye. The version in Debian's repo will be updated as per Debian's normal packaging policy i.e. It won't be updated other than a critical security update. 

Meanwhile, our apt.mopidy.com repo provides all free and non-free Mopidy-related packages, including the latest releases. Currently and until April 2022 they are built in a way that makes them compatible for use on Buster, those are fine to use on Bullseye also. After April 2022 we'll drop our apt.mopidy.com support for Buster and future apt.mopidy.com packages will be built for Bullseye specifically. 

> Is it possible to maintain the nonfree packages for Debian Bullseye here?

That's exactly what apt.mopidy.com is doing today and will continue doing (until some time after the next Debian release).

So take https://apt.mopidy.com/buster.list and `s/buster/bullseye/` and you should be good. 

Hope that helps.

**Comment by peter-vanpoucke** [comment]
Crystal clear. Thanks for the elaborate answer.

I'll take a note to swap buster with bullseye in the mopidy list, somewhere around April.
