### ISSUE TITLE
Public key not available 

### ISSUE THREAD

**Issue by s-martin** [mopidy/apt#23]
When installing https://github.com/MiczFlor/RPi-Jukebox-RFID our users get the error

```
W: GPG error: https://apt.mopidy.com buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78FD980E271D2943
```

Has the key been changed or is it only available for bullseye and not for buster?

**Comment by jodal** [comment]
The same key is used to sign both buster (which will have no further updates) and bullseye. Does the problem persist it they try following the instructions at https://docs.mopidy.com/en/latest/installation/debian/ again?

**Comment by s-martin** [comment]
Thanks, looks like the path to keyrings changed from /usr/local to /etc/apt

**Comment by jodal** [comment]
Yeah, that was changed a few days ago after some research by @kingosticks and @adamcik, where they concluded that was the proper location.

In practice, it doesn't matter, as long as the public key file's path in `/etc/apt/sources.list.d/mopidy.list` is correct.

**Comment by kingosticks** [comment]
@s-martin out of interest, how were your users hitting this? Do you have your own version of our install instructions or a script relying on that location? No plans to fiddle with it again but next time I can drop you a note if that helps.

**Comment by s-martin** [comment]
We use it here
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/3e9fc2520aaabed09e922f024e8c2e56102000e4/scripts/installscripts/buster-install-default.sh#L788

and here
https://github.com/MiczFlor/RPi-Jukebox-RFID/blob/3e9fc2520aaabed09e922f024e8c2e56102000e4/scripts/installscripts/buster-install-default.sh#L837
