### ISSUE TITLE
Packages for Bullseye

### ISSUE THREAD

**Issue by georgkrause** [mopidy/apt#5]
Debian Bullseye is close. Just wanted to ask if there are any plans to provide the amazing apt repository for bullseye, too? Or should we just use the one from buster?

**Comment by jodal** [comment]
First of all, I should mention that all packages in this repo in their current version will be part of Debian `bullseye`, except the packages related to Spotify, which you'll only find here.

My current plan is approximately:

As long as I build new packages on `buster`, that'll be the dist to use. Once the latest Ubuntu LTS is newer than the latest Debian stable, e,g. around April 2022, I'll switch to building packages on `bullseye` instead. At that point I'll create a `bullseye` dist, starting out as a copy of the `buster` dist. and only publish new releases in the `bullseye` dist. From here on out, the `buster` dist will not see any new releases but will stay around until `buster` reaches end-of-life.

**Comment by georgkrause** [comment]
thanks for the info! Getting mopidy into official Debian bullseye is a great thing. But this package will be outdated some time, so its important to keep the mopidy repo. Great to hear there will be a switch, thanks for letting me know about the plan!
